language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  allow_failures:
  - python: "2.7"
# command to install dependencies
install:
  - pip install pytest
  - python setup.py install
# command to run tests
script:
  - pytest tests/
