language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  allow_failures:
  - python: "2.7"
# command to install dependencies
install:
  - pip install pytest pytest-cov -U
  - python setup.py install
# command to run tests
script:
  - pytest --cov=scikit_tt tests/
after_script:
  - bash <(curl -s https://codecov.io/bash)
